# Generated by Django 5.0.6 on 2024-06-02 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryDjango', '0011_category_alter_dish_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_secret',
            field=models.BooleanField(default=False),
        ),
    ]
